### PR TITLE
Added Button Component

### PR DESCRIPTION
**Pull request by jbennink**
Added the Button component and the sample page ui/buttons.

### CODE REVIEW

**Comment by sjefvanleeuwen** [comment]
Hi, 

We are currently not convinced yet to componentize all the specific molecular elements by hand that are note specifcally styled by AdminLTE (other than bootstrap). If you look in te integration project, we adopt the Blazorised.Bootstrap as second dependency to adopt such elements (integration).

What are your thoughts?

See button page and namespacings in:
https://github.com/sjefvanleeuwen/blazorized-adminlte-plugins

**Comment by jbennink** [comment]
I also wonder how far you should go. I did not know about Blazorise.Bootstrap. This package is not part of the Site or Site.Shared projects yet? Should I add it separate when I use the Blazor.AdminLte project?
I wanted to convert more pages from the AdminLte demo site, so that would mean Blazorise.Boorstrap should be added to Site.Shared? 
If so I can amend this pull request to change it to use their Button.

Extra: You currently have a Color enum, but Blazorise also has Color, should that merge or do they stay separate?

**Comment by sjefvanleeuwen** [comment]
The project https://github.com/sjefvanleeuwen/blazorized-adminlte-plugins show integration with Blazorise.Bootstrap buttons. That will stay a seperate project.

If we make blazorise.bootstrap part of this project, people will not have the opportunity to use another framework such as MatBlazor bootstrap. Hence we will keep the Color seperate. Intellisense will automatically choose the correct enumeration for the choosen framework.

A down side is... that if you include Blazorize.Bootstrap you will have to make a distinction because there will be some ambiguity. For Example <Card> wil become something like <Blazor.AdminLte.Card>. Respectively <Card> for Blazorise.Bootstrap wil become something like <Blazorise.Card>  Although that is the primary intention for namespaces.

In otherwords different compontentization frameworks can be easily integrated through namespacing and work in unison.

**Comment by jbennink** [comment]
Isn't Site the Site you , the user, makes so taking a dependency there would be fine.? Blazorise.AdminLte is de source for the nuget package? Correct?
If you don't want to take a dependency on Blazorise.Bootstrap or whatever then you really can't create all of the controls that are part of the AdminLte template, or am I missing something here?

**Comment by jbennink** [comment]
Are your intentions with Blazor.AdminLte to create only the controls *not* part of Blazorise?

Then I wonder why Card and Carousel were started. Those are already in Blazorise. I think that is not a bad Idea, even though my changed Buttons page now looks less clean because of all the namespaces. I guess I could alias some to make them easier to read.

**Comment by jbennink** [comment]
To continue this discussion about project layout and how to separate things I have some more questions. Just curious and want to learn how other do things.

Question: Was I correct in adding the Blazorise dependency to the Site.Shared project? 

Question: Is it correct to assume the Blazor.AdminLte.Site and Blazor.AdminLte.Site.Shared projects are "copied" and changed/used to create you "app" and the Blazor.AdminLte is taken as a nuget dependency?

Question: What is the reason to have a Blazor.AdminLte.Content project that has copied versions of all javascript libraries instead of using LibMan?

**Comment by sjefvanleeuwen** [comment]
@jbennink do you want a microsoft teams session?  So we can take you through the concepts. That might be easier to explain.

**Comment by jbennink** [comment]
> @jbennink do you want a microsoft teams session? So we can take you through the concepts. That might be easier to explain.

Yep on my work email, no problem that probably works faster

**Comment by sjefvanleeuwen** [comment]
I have come to the same conclusion, in regards to missing styles on the blazorise bootstrap components. I have commited the initial proposal  and reverted blazorise for record.

**Pull request merged**
